In [2]:
import numpy as np
x = [2, 3, 4.0, 9.1]
y = np.array(x)
print(y)

[2.  3.  4.  9.1]


In [3]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
x = np.zeros((3, 4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
print(x.shape)
print(x.ndim)
print(x.size)

(3, 4)
2
12


In [11]:
x + 6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [14]:
x = [1, 2, 3, 4, 5]
y = [i + 5 for i in x]
print(y)

[6, 7, 8, 9, 10]


In [15]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(3, 4) * 100

array([[66.33344361, 77.496247  , 58.03734442, 10.43115676],
       [75.42709406, 69.32243743, 70.49196628, 89.97702627],
       [ 8.84575304, 90.21921843, 71.2062418 , 90.67357468]])

In [21]:
np.random.randn(3, 4) * 1000

array([[ 1079.63635999,   674.2926385 ,  1369.81861155,   412.85999155],
       [  223.0374476 , -1478.88147499,  1102.68161569,  -845.29657956],
       [ -325.97368657,   305.63599669,  2454.2602169 ,   150.78187536]])

In [3]:
np.random.seed(10)
x = np.random.randint(0, 10, (3, 3))
x

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9]])

In [5]:
x[1:2,1:2]

array([[9]])

In [82]:
x.sum(axis = 1)

array([13, 10, 18])

In [86]:
x = np.random.randint(1, 10, (30, 40))
y = np.random.randint(10, 20, (40, 30))
print(x.shape, y.shape)

(30, 40) (40, 30)


In [89]:
# print(np.matmul(x, y))
# print(x @ y)

In [97]:
np.random.seed(42)
x = np.random.randint(10, 30, (3, 2, 4, 3))

In [124]:
x

array([[[[16, 29, 24],
         [20, 17, 16],
         [28, 20, 20],
         [13, 17, 12]],

        [[11, 21, 15],
         [11, 10, 21],
         [21, 26, 19],
         [25, 24, 24]]],


       [[[28, 21, 29],
         [12, 14, 28],
         [16, 18, 16],
         [27, 13, 23]],

        [[27, 18, 11],
         [29, 24, 16],
         [21, 17, 24],
         [12, 23, 26]]],


       [[[13, 27, 17],
         [13, 11, 15],
         [19, 13, 27],
         [21, 11, 19]],

        [[13, 23, 25],
         [24, 17, 23],
         [17, 25, 22],
         [27, 24, 22]]]])

In [126]:
x[2, 0, :3 ,:]

array([[13, 27, 17],
       [13, 11, 15],
       [19, 13, 27]])

In [127]:
x.dtype

dtype('int32')

In [104]:
y = np.random.randint(10, 20, (3, 4, 4))
y

array([[[12, 10, 12, 14],
        [12, 10, 14, 19],
        [16, 16, 18, 19],
        [19, 12, 16, 10]],

       [[13, 13, 14, 16],
        [16, 13, 16, 12],
        [15, 11, 19, 18],
        [14, 15, 13, 19]],

       [[16, 18, 16, 10],
        [10, 18, 18, 13],
        [18, 12, 16, 15],
        [17, 18, 14, 10]]])

In [106]:
y[1:, 1:3, 1:]

array([[[13, 16, 12],
        [11, 19, 18]],

       [[18, 18, 13],
        [12, 16, 15]]])

In [1]:
import numpy as np

In [26]:
x = np.arange(1, 21) # vector
y = x.reshape(-1, 5).reshape(2, 2, 5)
print(x.shape)
print(y.shape)

(20,)
(2, 2, 5)


In [27]:
print(y)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [33]:
x = np.linspace(1, 3, 10)
x[np.newaxis, :] # x.reshape(1, -1)

array([[1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
        2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ]])

In [37]:
x = np.random.randint(10, 100, (4, 5))
x

array([[12, 71, 68, 28, 95],
       [44, 90, 80, 26, 47],
       [75, 28, 92, 38, 75],
       [11, 46, 22, 30, 18]])

In [41]:
x.max(axis = 0)

array([75, 90, 92, 38, 95])

In [52]:
x = np.array([2, 3, 4, 5, np.nan])
x

array([ 2.,  3.,  4.,  5., nan])

In [54]:
np.nansum(x)

14.0

In [48]:
np.nan + 2

nan

In [ ]:
np.random.randn(

In [58]:
x = np.random.randint(1,100,(2,3,1,2))
x

array([[[[41, 59]],

        [[22, 26]],

        [[88, 36]]],


       [[[20, 59]],

        [[28, 83]],

        [[22, 58]]]])

In [7]:
np.ones(3,int)

array([1, 1, 1])